from typing import Any, Optional

from pydantic import BaseModel, ConfigDict, Field


# ==========================================================
# BASE WORK MODEL
# ==========================================================

class WorkRecord(BaseModel):
    """
    Flexible representation of a MPLADS work record.

    The ML dataset contains many dynamically generated feature
    columns, so extra fields are allowed.
    """

    model_config = ConfigDict(extra="allow")

    work_id: Optional[str] = None


# ==========================================================
# HEALTH RESPONSE
# ==========================================================

class HealthResponse(BaseModel):

    status: str
    message: str


# ==========================================================
# ROOT RESPONSE
# ==========================================================

class RootResponse(BaseModel):

    message: str
    api_base: str
    docs: str


# ==========================================================
# DATASET STATISTICS
# ==========================================================

class DatasetStatsResponse(BaseModel):

    total_works: int

    columns: list[str]

    missing_values: dict[str, int]

    duplicate_count: int


# ==========================================================
# PAGINATED WORKS RESPONSE
# ==========================================================

class WorksResponse(BaseModel):

    total: int

    limit: int

    offset: int

    data: list[WorkRecord]


# ==========================================================
# ANOMALY RECORD
# ==========================================================

class AnomalyRecord(WorkRecord):
    """
    Represents a work flagged by the anomaly detection pipeline.

    Extra feature columns are still allowed because the ML pipeline
    may generate additional fields.
    """

    anomaly_score: Optional[float] = None

    anomaly_label: Optional[bool] = None

    anomaly_severity: Optional[str] = None

    anomaly_category: Optional[str] = None

    explanation: Optional[Any] = None


# ==========================================================
# PAGINATED ANOMALIES RESPONSE
# ==========================================================

class AnomaliesResponse(BaseModel):

    total_anomalies: int

    limit: int

    offset: int

    data: list[AnomalyRecord]


# ==========================================================
# ANOMALY COUNT RESPONSE
# ==========================================================

class AnomalyCountResponse(BaseModel):

    total_anomalies: int


# ==========================================================
# HIGH-RISK ANOMALIES RESPONSE
# ==========================================================

class HighRiskAnomaliesResponse(BaseModel):

    count: int

    data: list[AnomalyRecord]


# ==========================================================
# ANOMALY SUMMARY RESPONSE
# ==========================================================

class AnomalySummaryResponse(BaseModel):
    """
    Flexible model for anomaly_summary.json.

    The exact structure is generated by the ML pipeline and may
    evolve as the pipeline changes.
    """

    model_config = ConfigDict(extra="allow")


# ==========================================================
# GENERIC ERROR RESPONSE
# ==========================================================

class ErrorResponse(BaseModel):

    detail: str