from pathlib import Path
import json

import pandas as pd
from fastapi import APIRouter, HTTPException, Query

from .data_processor import (
    load_features,
    get_total_works,
    get_columns,
    get_missing_values,
    get_duplicate_count,
    get_work_by_id,
)

from .models import (
    HealthResponse,
    DatasetStatsResponse,
    WorksResponse,
    WorkRecord,
    AnomaliesResponse,
    AnomalyRecord,
    AnomalyCountResponse,
    HighRiskAnomaliesResponse,
    AnomalySummaryResponse,
)


# ==========================================================
# ROUTER
# ==========================================================

router = APIRouter()


# ==========================================================
# PROJECT PATHS
# ==========================================================

# routes.py is located at:
# SIH26102/backend/app/routes.py
#
# parents[2] gives:
# SIH26102/

PROJECT_ROOT = Path(__file__).resolve().parents[2]

# ML pipeline outputs are located at:
# SIH26102/ml/outputs/

ML_OUTPUT_DIR = PROJECT_ROOT / "ml" / "outputs"

ANOMALY_SCORES_FILE = (
    ML_OUTPUT_DIR / "anomaly_scores.csv"
)

ANOMALY_FLAGGED_FILE = (
    ML_OUTPUT_DIR / "anomaly_flagged.csv"
)

ANOMALY_SUMMARY_FILE = (
    ML_OUTPUT_DIR / "anomaly_summary.json"
)


# ==========================================================
# HELPER FUNCTIONS
# ==========================================================

def dataframe_to_records(df: pd.DataFrame):
    """
    Convert a DataFrame into JSON-safe records.
    Handles NaN values correctly.
    """

    return json.loads(
        df.to_json(
            orient="records",
            date_format="iso"
        )
    )


def load_anomaly_scores():
    """
    Load anomaly scores generated by the ML pipeline.
    """

    if not ANOMALY_SCORES_FILE.exists():

        raise FileNotFoundError(
            f"Anomaly scores file not found: "
            f"{ANOMALY_SCORES_FILE}"
        )

    return pd.read_csv(
        ANOMALY_SCORES_FILE
    )


def load_flagged_anomalies():
    """
    Load only flagged anomalies generated by the ML pipeline.
    """

    if not ANOMALY_FLAGGED_FILE.exists():

        raise FileNotFoundError(
            f"Flagged anomalies file not found: "
            f"{ANOMALY_FLAGGED_FILE}"
        )

    return pd.read_csv(
        ANOMALY_FLAGGED_FILE
    )


def load_anomaly_summary():
    """
    Load the ML pipeline summary JSON.
    """

    if not ANOMALY_SUMMARY_FILE.exists():

        raise FileNotFoundError(
            f"Anomaly summary file not found: "
            f"{ANOMALY_SUMMARY_FILE}"
        )

    with open(
        ANOMALY_SUMMARY_FILE,
        "r",
        encoding="utf-8"
    ) as file:

        return json.load(file)


# ==========================================================
# HEALTH CHECK
# ==========================================================

@router.get(
    "/health",
    response_model=HealthResponse
)
def health_check():

    return {
        "status": "ok",
        "message": "MPLADS Anomaly Detection API is running"
    }


# ==========================================================
# DATASET STATISTICS
# ==========================================================

@router.get(
    "/stats",
    response_model=DatasetStatsResponse
)
def get_dataset_stats():

    df = load_features()

    return {
        "total_works": get_total_works(df),
        "columns": get_columns(df),
        "missing_values": get_missing_values(df),
        "duplicate_count": get_duplicate_count(df),
    }


# ==========================================================
# ANOMALY SUMMARY
# ==========================================================

@router.get(
    "/summary",
    response_model=AnomalySummaryResponse
)
def get_summary():

    try:

        summary = load_anomaly_summary()

        return summary

    except FileNotFoundError as error:

        raise HTTPException(
            status_code=404,
            detail=str(error)
        )


# ==========================================================
# GET ALL WORKS
# ==========================================================

@router.get(
    "/works",
    response_model=WorksResponse
)
def get_works(

    limit: int = Query(
        default=100,
        ge=1,
        le=1000
    ),

    offset: int = Query(
        default=0,
        ge=0
    ),
):

    df = load_features()

    total = len(df)

    # Standard pagination slice
    paginated_df = df.iloc[
        offset : offset + limit
    ]

    return {
        "total": total,
        "limit": limit,
        "offset": offset,
        "data": dataframe_to_records(
            paginated_df
        ),
    }


# ==========================================================
# GET SINGLE WORK
# ==========================================================

# IMPORTANT:
# work_id values contain "/" characters.
#
# Example:
# WS/MP005/2024-2025/145074
#
# Therefore we use {work_id:path} so FastAPI
# accepts the complete ID.

@router.get(
    "/works/{work_id:path}",
    response_model=WorkRecord
)
def get_work(work_id: str):

    df = load_features()

    work = get_work_by_id(
        df,
        work_id
    )

    if work is None:

        raise HTTPException(
            status_code=404,
            detail=(
                f"Work with ID "
                f"'{work_id}' was not found"
            )
        )

    # Convert safely to JSON
    return json.loads(
        pd.DataFrame([work]).to_json(
            orient="records",
            date_format="iso"
        )
    )[0]


# ==========================================================
# GET ALL FLAGGED ANOMALIES
# ==========================================================

@router.get(
    "/anomalies",
    response_model=AnomaliesResponse
)
def get_anomalies(

    limit: int = Query(
        default=100,
        ge=1,
        le=1000
    ),

    offset: int = Query(
        default=0,
        ge=0
    ),
):

    try:

        anomalies = load_flagged_anomalies()

        total = len(anomalies)

        # Standard pagination slice
        paginated_anomalies = anomalies.iloc[
            offset : offset + limit
        ]

        return {
            "total_anomalies": total,
            "limit": limit,
            "offset": offset,
            "data": dataframe_to_records(
                paginated_anomalies
            ),
        }

    except FileNotFoundError as error:

        raise HTTPException(
            status_code=404,
            detail=str(error)
        )


# ==========================================================
# GET ANOMALY COUNT
# ==========================================================

@router.get(
    "/anomalies/count",
    response_model=AnomalyCountResponse
)
def get_anomaly_count():

    try:

        anomalies = load_flagged_anomalies()

        return {
            "total_anomalies": len(anomalies)
        }

    except FileNotFoundError as error:

        raise HTTPException(
            status_code=404,
            detail=str(error)
        )


# ==========================================================
# GET HIGH-RISK ANOMALIES
# ==========================================================

@router.get(
    "/anomalies/high-risk",
    response_model=HighRiskAnomaliesResponse
)
def get_high_risk_anomalies(

    top_n: int = Query(
        default=10,
        ge=1,
        le=100
    ),
):

    try:

        anomalies = load_flagged_anomalies()

        if "anomaly_score" not in anomalies.columns:

            raise HTTPException(
                status_code=500,
                detail=(
                    "anomaly_score column "
                    "not found in anomaly output"
                )
            )

        high_risk = anomalies.sort_values(
            by="anomaly_score",
            ascending=False
        ).head(top_n)

        return {
            "count": len(high_risk),
            "data": dataframe_to_records(
                high_risk
            ),
        }

    except FileNotFoundError as error:

        raise HTTPException(
            status_code=404,
            detail=str(error)
        )


# ==========================================================
# GET SINGLE ANOMALY
# ==========================================================

@router.get(
    "/anomalies/{work_id:path}",
    response_model=AnomalyRecord
)
def get_anomaly_by_work_id(
    work_id: str
):

    try:

        anomalies = load_flagged_anomalies()

        result = anomalies[
            anomalies["work_id"] == work_id
        ]

        if result.empty:

            raise HTTPException(
                status_code=404,
                detail=(
                    f"No flagged anomaly found "
                    f"for work ID '{work_id}'"
                )
            )

        return dataframe_to_records(
            result
        )[0]

    except FileNotFoundError as error:

        raise HTTPException(
            status_code=404,
            detail=str(error)
        )